appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
travis:
  secure: {BINSTAR_TOKEN: TpdF3zXPC5cGNYDIj5W+rQSIQyMltAsTDueu1F/4ALow32biALWhl5idjku1CkUp+wwY9CKaWxvTOjgiwDCiO8LcJY8XZG5WVMm30CAy3Bd9ptV+R30tJX7uJfB/6j3DF+YMt0cad5UkOYNszrUnjlgWaQ35jhbX3N15OUqvgJw8OTb0mtcgRuvpsEzZrNmzin4kkJp5VIKFcpzeLJNyYq6lPU41CuVdvDRMEugUClbrGiPPVZATlh1DmiqhkmlgJW3g0OcB4cF3fOKCN0XDUKLudwUKzmo537bbvk/j9K4ewLLAEqL5tLFOgMUqbpV+m2r+i0S7/tPgyZ7ZcVBFuokdZQDw55NzalGDpwVNWyrLh3sWLN+Q41E1K5+BuFzRtpdhFzBl95P2O6okh38Qu2GvPa8/1yb9kU8hj7+sCaLnLZDOfnjLEOdGU80FXysYve/xLfBnDNRgS7DuazpZbOAZI2Oqw0s2Nl07FCR4/CA4WE/nXxuZoM0oTi1FBNMlNX/z9xQpIX203KWORwG6w9dSIMklAH53dCuglXpYMaafZdIFtYPqgW3qAd1BjVWILd42mSYzyBM5zxao82YM7B9FRSaYClPdLuFqFfsi4RAH1LyegEpin83gFuDgKSyxSQ0+j5bGa6wGIgtCHi/qAboXw89irnwGTceyTxJLM3c=}
provider:
  win: azure
